"""Task Memory layer.

Task Memory describes the boundary and goal of the **current** session:
"focus on industrial electrical risk", "produce this week's remediation
checklist", etc. It is generated by the Planner at
session start and is **actively reset** by the system when the scene or the
top-level goal changes — preventing rules and goals from cross-contaminating
between sessions.

This module:
- accepts the latest planner output and persists it onto the chat session,
- detects scene change vs. the previously persisted session scene and bumps
  the goal version with reset_reason="scene_change",
- assembles the per-turn Task Memory view consumed by the Agent.
"""
from __future__ import annotations

import json
from typing import Any, Dict, Optional

from sqlalchemy.orm import Session

from app.db import crud
from app.services.memory.core_memory import core_rules
from app.services.scene_guides import scene_guides_service


def _safe_text(value: Any, max_len: int = 220) -> str:
    return str(value or "").strip()[:max_len]


def _normalize_intent(planner_intent: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Reduce the raw planner output to the small, stable shape we want to
    persist as Task Memory state."""
    if not isinstance(planner_intent, dict):
        return {}
    needs = {
        key: bool(planner_intent.get(key))
        for key in (
            "needs_rules",
            "needs_history",
            "needs_insights",
            "needs_production_safety",
            "needs_record_detail",
        )
    }
    return {
        "goal": _safe_text(planner_intent.get("goal"), 300),
        "scene": _safe_text(planner_intent.get("scene"), 40),
        "response_style": _safe_text(planner_intent.get("response_style"), 30),
        "record_id": _safe_text(planner_intent.get("record_id"), 60),
        **needs,
    }


def build_task_context(
    *,
    session_id: str,
    scene: str,
    user_message: str,
    current_record_context: Optional[Dict[str, Any]],
    short_term_memory: Dict[str, Any],
    db: Optional[Session] = None,
    planner_intent: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    record = (current_record_context or {}).get("record") or {}
    scene_guide = scene_guides_service.get_guide(scene)
    intent_summary = _normalize_intent(planner_intent)

    # Default state when no DB context is available (snapshot endpoint with no
    # active session). Keep deterministic shape.
    persisted_goal = ""
    persisted_intent: Dict[str, Any] = {}
    goal_version = 1
    reset_reason = ""

    if db is not None and session_id:
        session = crud.get_chat_session(db, session_id)
        prev_scene = _safe_text(getattr(session, "scene", "") if session else "", 40)
        prev_version = int(getattr(session, "goal_version", 1) or 1) if session else 1
        prev_intent_raw = getattr(session, "current_task_intent_json", "") if session else ""
        try:
            prev_intent = json.loads(prev_intent_raw) if prev_intent_raw else {}
            if not isinstance(prev_intent, dict):
                prev_intent = {}
        except Exception:
            prev_intent = {}

        bump = False
        reason = ""
        if session and prev_scene and scene and prev_scene.lower() != _safe_text(scene, 40).lower():
            bump = True
            reason = "scene_change"
        elif intent_summary.get("goal") and prev_intent.get("goal") and intent_summary["goal"] != prev_intent.get("goal"):
            bump = True
            reason = "goal_change"

        new_goal: Optional[str] = None
        new_intent: Optional[Dict[str, Any]] = None
        if intent_summary:
            new_goal = intent_summary.get("goal") or _safe_text(user_message, 200)
            new_intent = intent_summary
        elif user_message:
            new_goal = _safe_text(user_message, 200)

        if session and (new_goal is not None or new_intent is not None or bump):
            updated = crud.update_chat_session_task_state(
                db,
                session_id,
                goal=new_goal,
                intent=new_intent,
                reset_reason=reason if bump else "",
                bump_version=bump,
                new_scene=scene if bump else None,
            )
            session = updated or session

        if session:
            persisted_goal = _safe_text(getattr(session, "current_task_goal", ""), 400)
            try:
                persisted_intent = json.loads(getattr(session, "current_task_intent_json", "") or "{}")
                if not isinstance(persisted_intent, dict):
                    persisted_intent = {}
            except Exception:
                persisted_intent = {}
            goal_version = int(getattr(session, "goal_version", 1) or 1)
            reset_reason = _safe_text(getattr(session, "goal_reset_reason", ""), 60)
        else:
            goal_version = prev_version

    # When no DB session, fall back to whatever the planner gave us this turn.
    effective_goal = persisted_goal or intent_summary.get("goal") or _safe_text(user_message, 200)
    effective_intent = persisted_intent or intent_summary

    return {
        "session_id": session_id,
        "scene": scene,
        "user_goal": _safe_text(effective_goal, 400),
        "task_goal": _safe_text(effective_goal, 400),
        "planner_intent": effective_intent,
        "goal_version": goal_version,
        "goal_reset_reason": reset_reason,
        "short_term_summary": _safe_text(short_term_memory.get("summary"), 300),
        "current_record_id": _safe_text(record.get("record_id"), 60),
        "current_record_risk": _safe_text(record.get("overall_risk"), 40),
        "current_record_summary": _safe_text(record.get("summary"), 220),
        "core_rules": core_rules(db=db, scene=scene),
        "scene_guide": {
            "title": _safe_text(scene_guide.get("title"), 120),
            "poem": _safe_text(scene_guide.get("poem"), 120),
            "focus_area": _safe_text(scene_guide.get("focus_area"), 120),
            "checklist": [_safe_text(x, 120) for x in (scene_guide.get("checklist") or [])[:8]],
            "tips": [_safe_text(x, 120) for x in (scene_guide.get("tips") or [])[:5]],
        },
    }
