from pathlib import Path
from typing import Optional

from pydantic_settings import BaseSettings, SettingsConfigDict


BASE_DIR = Path(__file__).resolve().parents[2]
ENV_FILE = BASE_DIR / ".env"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=str(ENV_FILE),
        case_sensitive=False,
        extra="ignore",
    )

    BASE_DIR: Path = BASE_DIR
    DATABASE_URL: str = f"sqlite:///{BASE_DIR}/app.db"

    UPLOAD_DIR: Path = BASE_DIR / "uploads"
    MAX_UPLOAD_SIZE: int = 10 * 1024 * 1024
    ALLOWED_EXTENSIONS: set[str] = {".jpg", ".jpeg", ".png", ".webp"}

    API_V1_PREFIX: str = "/api/v1"

    SILICONFLOW_API_KEY: Optional[str] = None
    SILICONFLOW_BASE_URL: str = "https://api.siliconflow.cn/v1"
    SILICONFLOW_VISION_MODEL: str = "qwen-vl-max"
    SILICONFLOW_TEXT_MODEL: str = "qwen-plus"

    RESULT_CACHE_ENABLED: bool = True
    RESULT_CACHE_TTL_SECONDS: int = 7 * 24 * 60 * 60
    RESULT_CACHE_DIR: Path = BASE_DIR / "cache" / "analysis_results"
    RAG_EMBEDDING_CACHE_DIR: Path = BASE_DIR / "cache" / "rag_embeddings"
    LONG_MEMORY_CACHE_DIR: Path = BASE_DIR / "cache" / "long_term_memory"
    LONG_MEMORY_INDEX_FILE: Path = BASE_DIR / "cache" / "long_term_memory" / "case_index.json"
    LONG_MEMORY_ENABLE_EMBEDDING: bool = True
    LONG_MEMORY_EMBEDDING_MODEL: str = "BAAI/bge-m3"
    LONG_MEMORY_BATCH_SIZE: int = 16
    LONG_MEMORY_MAX_CASES: int = 800
    LONG_MEMORY_TOP_K: int = 3
    LONG_MEMORY_SCENE_BONUS: float = 0.08
    # Thesis §5.7.4: μ weights vector vs lexical similarity in long-term retrieval.
    # When embedding is available, score = μ * sim_dense + (1 - μ) * sim_lex + scene_bonus.
    # When embedding is unavailable, μ degrades to 0 (pure lexical).
    LONG_MEMORY_MU: float = 0.8

    # Thesis §5.7.3: short-term memory persists "raw + summary + metadata".
    # Summary may be generated by a small LLM every N turns; otherwise the
    # deterministic stitched summary is used as a fallback.
    SHORT_MEMORY_LLM_SUMMARY: bool = False
    SHORT_MEMORY_SUMMARY_EVERY_N: int = 4
    SHORT_MEMORY_SUMMARY_MAX_TOKENS: int = 240

    # Thesis §5.7.1: writes to Core Memory require admin permission. The token
    # must be supplied via the X-Admin-Token header on all mutating endpoints.
    # When unset (None), writes are blocked entirely — read-only by default.
    ADMIN_TOKEN: Optional[str] = None

    RULES_FILE: Path = BASE_DIR / "app" / "data" / "fire_rules.json"
    SCENE_GUIDES_FILE: Path = BASE_DIR / "app" / "data" / "scene_guides.json"
    PRODUCTION_SAFETY_FILE: Path = BASE_DIR / "app" / "data" / "production_safety_playbook.json"
    PRODUCTION_SAFETY_TOP_K: int = 5
    RAG_TOP_K: int = 3
    RAG_MIN_SCORE: float = 2.0
    RAG_MIN_TOKEN_HITS: int = 1
    RAG_RETRIEVAL_MODE: str = "hybrid"  # keyword | vector | hybrid
    RAG_VECTOR_WEIGHT: float = 0.55
    RAG_LEXICAL_WEIGHT: float = 0.45
    RAG_MIN_VECTOR_SCORE: float = 0.12
    RAG_SCENE_BONUS: float = 0.08
    RAG_ENABLE_QUERY_REWRITE: bool = True
    RAG_QUERY_REWRITE_USE_LLM: bool = True
    RAG_MULTI_QUERY_MAX: int = 4
    RAG_SUBQUERY_MAX: int = 3
    RAG_ENABLE_DENSE_RETRIEVAL: bool = True
    RAG_EMBEDDING_MODEL: str = "BAAI/bge-m3"
    RAG_EMBEDDING_BATCH_SIZE: int = 16
    RAG_DENSE_WEIGHT: float = 0.15
    RAG_MIN_DENSE_SCORE: float = 0.2
    RAG_ENABLE_RERANK: bool = True
    RAG_RERANK_MODEL: str = "BAAI/bge-reranker-v2-m3"
    RAG_RERANK_TOP_N: int = 6
    RAG_RERANK_WEIGHT: float = 0.35
    RAG_ENABLE_DYNAMIC_TOP_K: bool = True
    RAG_TOP_K_MAX: int = 6
    RAG_ENABLE_DYNAMIC_QUERY_BUDGET: bool = True
    RAG_QUERY_BUDGET_USE_SIGMOID: bool = True
    RAG_QUERY_BUDGET_SIMPLE: int = 2
    RAG_QUERY_BUDGET_MEDIUM: int = 4
    RAG_QUERY_BUDGET_HARD: int = 8
    RAG_QUERY_BUDGET_TOKEN_THRESHOLD_SIMPLE: int = 14
    RAG_QUERY_BUDGET_TOKEN_THRESHOLD_MEDIUM: int = 28
    RAG_QUERY_BUDGET_LAMBDA_LENGTH: float = 0.03
    RAG_QUERY_BUDGET_LAMBDA_HAZARD: float = 0.45
    RAG_QUERY_BUDGET_LAMBDA_INDUSTRIAL: float = 0.70
    RAG_QUERY_BUDGET_LAMBDA_CONFLICT: float = 0.35
    RAG_QUERY_BUDGET_SIGMOID_ETA: float = 0.80
    RAG_QUERY_BUDGET_SIGMOID_CENTER: float = 1.20
    RAG_ENABLE_MMR_SELECTION: bool = True
    RAG_MMR_LAMBDA: float = 0.72
    RAG_MMR_CANDIDATE_MULTIPLIER: int = 3
    RAG_ENABLE_SET_SELECTION: bool = True
    RAG_SET_SELECTION_RELEVANCE_WEIGHT: float = 0.80
    RAG_SET_SELECTION_NOVELTY_WEIGHT: float = 0.15
    RAG_SET_SELECTION_SOURCE_DIVERSITY_WEIGHT: float = 0.03
    RAG_SET_SELECTION_HAZARD_DIVERSITY_WEIGHT: float = 0.02
    RAG_SET_SELECTION_FAMILY_REPEAT_PENALTY: float = 0.0
    RAG_SET_SELECTION_MIN_GAIN: float = 0.01
    RAG_SET_SELECTION_SOURCE_NORM_ENABLED: bool = True
    RAG_ENABLE_EVIDENCE_TREE_SEARCH: bool = True
    RAG_EVIDENCE_TREE_PATH_BONUS: float = 0.06
    RAG_EVIDENCE_TREE_HAZARD_BRANCH_MAX: int = 4
    RAG_EVIDENCE_TREE_AGGREGATE_PATHS: bool = True
    RAG_ENABLE_TEXT_REPAIR: bool = True
    RAG_ENABLE_HAZARD_HINT_ROUTING: bool = True
    RAG_HAZARD_HINT_BONUS: float = 0.12


settings = Settings()

